version: '3.8'
services:
  no-disposable-email:
    restart: unless-stopped
    container_name: no-disposable-email
    image: yassirh/no-disposable-email:latest
    ports:
      - "3000:3000"
    healthcheck:
      test: [
          "CMD", "node", "-e",
          "require('http').get('http://localhost:3000/heartbeat',res=>process.exit(res.statusCode===200?0:1)).on('error',()=>process.exit(1))"
      ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
